config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", sessions: 'sessions', registrations: 'registrations'}
  resources :barbecues
  resources :ingredients

  root 'welcome#index'

  devise_scope :user do
    get '/user/sign_out' => 'devise/sessions#destroy'
  end

  resources :barbecues do
      resources :barbecue_ingredients, shallow: true
  end
  resources :barbecue_ingredients

  resources :barbecues do
      resources :supplies, shallow: true
  end
  resources :supplies

end

app/models/supply.rb
class Supply < ActiveRecord::Base
  validates :barbecue, :ingredient, :user, presence: true
  belongs_to :barbecue
  belongs_to :ingredient
  belongs_to :user

  after_create do |supply|
    Activity.create(action: "create_supply", extra_data: {supply_id: self.id}, barbecue: self.barbecue, user: supply.user)
  end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :set_supply, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit]

  # GET /supplies
  # GET /supplies.json
  def index
    @supplies = Supply.all
  end

  # GET /supplies/1
  # GET /supplies/1.json
  def show
  end

  # GET barbecue/1/supplies/new
  def new
    @barbecue = Barbecue.find params[:barbecue_id]
    @supply = Supply.new
    @contributions = Supply.where(supplies: {barbecue_id: @barbecue.id}).group(:ingredient_id).sum(:quantity)
  end

  # GET /supplies/1/edit
  def edit
  end

  # POST /supplies
  # POST /supplies.json
  def create
    @ingredient = Ingredient.find_or_initialize_by(title: supply_params[:ingredient][:title])
    @supply = Supply.new(quantity: supply_params[:quantity], ingredient: @ingredient)
    @barbecue = Barbecue.find params[:barbecue_id]
    @supply.ingredient = @ingredient
    @supply.barbecue = @barbecue
    @supply.user = current_or_guest_user

    respond_to do |format|
      if @supply.save
        format.html { redirect_to @supply.barbecue, notice: 'Supply was successfully created.' }
        format.json { render :show, status: :created, location: @supply }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1
  # PATCH/PUT /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to @supply, notice: 'Supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1
  # DELETE /supplies/1.json
  def destroy
    barbecue = @supply.barbecue
    @supply.destroy
    respond_to do |format|
      format.html { redirect_to barbecue_path(barbecue), notice: 'Supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_params
      params[:supply].permit(:quantity,:barbecue_id,:ingredient_id, ingredient: [:title])
    end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<div class="container">
  <div class="container col-md-8">
    <%= bootstrap_form_for([@barbecue, @supply], layout: :inline) do |f| %>
      <% if @supply.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@supply.errors.count, "error") %> prohibited this supply from being saved:</h2>
          <ul>
            <% @supply.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <h2><%= @barbecue.title %></h2>
      <div class="form-inline">
        <%= f.number_field :quantity, hide_label: :true,  :placeholder => "Type a quantity", required: :true %>
        <div class="form-group">
          <input class="form-control typeahead" name="supply[ingredient[title]]" placeholder="Type an ingredient" required="required"/>
        </div>
        <div class="actions">
          <% if user_signed_in? %>
            <%= f.submit :class => 'btn btn-success btn-lg'  %>
          <% else %>
            <%= render "devise/sessions/block_new" %>
          <% end %>
        </div>
      </div>
    <% end %>

  </div>
  <div class="container col-md-4 highlight">
    <h3>We need</h3>
    <% if @barbecue.barbecue_ingredient.count() > 0 %>
      <ul>
        <% @barbecue.barbecue_ingredient.each() do |barbecue_ingredient| %>
          <li><%= barbecue_ingredient.quantity %> <%= barbecue_ingredient.ingredient.title %></li>
        <% end %>
      </ul>
    <% else %>
      Nothing yet
    <% end %>
    <h3>We already have</h3>
    <% if @barbecue.supply.count() > 0 %>
      <ul>
        <% @barbecue.supply.each() do |supply| %>
          <li><%= supply.quantity %> <%= supply.ingredient.title %></li>
        <% end %>
      </ul>
    <% else %>
      Nothing yet
    <% end %>
  </div>
</div>

app/views/supplies/_onelineform.html.erb
<%= bootstrap_form_for([@barbecue, supply], remote: true) do |f| %>
  <div class="row">
    <div class="col-xs-3">
      <%= f.number_field :quantity, hide_label: :true, placeholder: "quantity" %>
    </div>
    <div class="col-xs-6">
      <input class="form-control typeahead" name="supply[ingredient[title]]" placeholder="Type an ingredient" required="required"/>
    </div>
    <div class="col-xs-3">
      <%= f.submit "Add", :class => 'btn btn-success btn-s' %>
    </div>
  </div>
<% end %>

app/views/supplies/create.js.erb
$('#we-have').append("<li><%= @supply.quantity %> <%= @supply.ingredient.title %></li>")
<% if current_or_guest_user.guest and current_or_guest_user.name == "Guest" %>
$('#name-div').modal()
<% end %>

app/views/supplies/edit.html.erb
<h1>Editing supply</h1>

<% if not user_signed_in? %>
  <p>Please <%= link_to 'login', new_user_session_path %></p>
<% else %>
    <%= bootstrap_form_for @supply do |f| %>
      <% if @supply.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@supply.errors.count, "error") %> prohibited this supply from being saved:</h2>
        <ul>
          <% @supply.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h2><%= @supply.barbecue.title %></h2>
    <p>
      I bring
      <%= f.number_field :quantity, :value => @supply.quantity, :placeholder => "2" %>
      <%= f.collection_select :ingredient_id, Ingredient.joins(:barbecue_ingredient), :id, :title, :value => @supply.ingredient %>
    </p>
    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>
<% end %>

<%= link_to 'Back to barbecue', barbecue_path(@supply.barbecue) %>

app/views/supplies/index.html.erb
<h1>Listing supplies</h1>

<table>
  <thead>
    <tr>
      <th>Who</th>
      <th colspan="2">What</th>
      <th>Where</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supplies.each do |supply| %>
      <tr>
        <td><%= supply.user.name %></td>
        <td><%= supply.quantity %></td>
        <td><%= supply.ingredient.title %></td>
        <td><%= supply.barbecue.title %></td>
        <td><%= link_to 'Show', supply %></td>
        <td><%= link_to 'Edit', edit_supply_path(supply) %></td>
        <td><%= link_to 'Destroy', supply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supply', new_supply_path %>

app/views/supplies/new.html.erb
<h1>New supply</h1>

<%= render 'form' %>

<%= link_to 'Back to barbecue', barbecue_path(@barbecue) %>

app/views/supplies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_supply_path(@supply) %> |
<%= link_to 'Back', supplies_path %>