config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", sessions: 'sessions', registrations: 'registrations'}
  resources :barbecues
  resources :ingredients

  root 'welcome#index'

  devise_scope :user do
    get '/user/sign_out' => 'devise/sessions#destroy'
  end

  resources :barbecues do
      resources :barbecue_ingredients, shallow: true
  end
  resources :barbecue_ingredients

  resources :barbecues do
      resources :supplies, shallow: true
  end
  resources :supplies

end

app/models/barbecue.rb
class Barbecue < ActiveRecord::Base
  has_many :barbecue_ingredient
  has_many :ingredient, :through => :barbecue_ingredient
  has_many :supply
  has_many :attending_user, :through => :supply
  belongs_to :user
  accepts_nested_attributes_for :barbecue_ingredient, allow_destroy: true, reject_if: lambda {|attributes| (attributes['quantity'].blank? || attributes['ingredient_attributes[title]'].blank?)}

  after_create do |supply|
    Activity.create(action: "create_barbecue", barbecue: self, user: self.user)
  end
end

app/controllers/barbecues_controller.rb
class BarbecuesController < ApplicationController
  before_action :set_barbecue, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit]
  require 'rqrcode'

  # GET /barbecues
  # GET /barbecues.json
  def index
    @barbecues = Barbecue.all
  end

  # GET /barbecues/1
  # GET /barbecues/1.json
  def show
    @attending_users = User.joins(:supply).where(supplies: {barbecue_id: @barbecue.id}).distinct
    # @contributions is an array associating ingredient_id to their total quantities
    @contributions = Supply.where(supplies: {barbecue_id: @barbecue.id}).group(:ingredient_id).sum(:quantity)
    @activities = Activity.where(barbecue_id: @barbecue.id).order("created_at DESC")
    if current_user
      @youbring = Supply.where(user: current_user).where(barbecue_id: @barbecue.id)
    else
      @youbring = []
    end
    @qr = RQRCode::QRCode.new(barbecue_url, :size => 7, :level => :l)
  end

  # GET /barbecues/new
  def new
    @barbecue = Barbecue.new
    3.times {
      @barbecue.barbecue_ingredient.build
      # Create fields for ingredients
      @barbecue.barbecue_ingredient.last.ingredient = Ingredient.new
    }
  end

  # GET /barbecues/1/edit
  def edit
    @barbecue.barbecue_ingredient.build  # Adds a field for an ingredient
    @barbecue.barbecue_ingredient.last.ingredient = Ingredient.new
  end

  # POST /barbecues
  # POST /barbecues.json
  def create
    @barbecue = Barbecue.new(barbecue_params)
    @barbecue.user = current_or_guest_user
    create_ingredients

    respond_to do |format|
      if @barbecue.save
        format.html { redirect_to @barbecue, notice: 'Barbecue was successfully created.' }
        format.json { render :show, status: :created, location: @barbecue }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @barbecue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barbecues/1
  # PATCH/PUT /barbecues/1.json
  def update
    create_ingredients

    respond_to do |format|
      if @barbecue.update(barbecue_params)
        format.html { redirect_to @barbecue, notice: 'Barbecue was successfully updated.' }
        format.json { render :show, status: :ok, location: @barbecue }
      else
        format.html { render :edit }
        format.json { render json: @barbecue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barbecues/1
  # DELETE /barbecues/1.json
  def destroy
    @barbecue.destroy
    respond_to do |format|
      format.html { redirect_to barbecues_url, notice: 'Barbecue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_barbecue
    @barbecue = Barbecue.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def barbecue_params
    params.require(:barbecue)
      .permit(
        :title,
        :description,
        :begin_at,
        barbecue_ingredient_attributes:
          [
            :id,
            :quantity,
            :_destroy,
            ingredient_attributes:
              [
                :id,
                :title
              ]
          ]
      )
  end

  def create_ingredients
    if params[:barbecue][:barbecue_ingredient_attributes]
      params[:barbecue][:barbecue_ingredient_attributes].each() do |index,local_params|
        if !(local_params[:quantity].blank?) && local_params[:ingredient_attributes][:title]
          if local_params[:id]
            barbecue_ingredient = BarbecueIngredient.find(local_params[:id])
          else
            barbecue_ingredient = BarbecueIngredient.new()
          end
          barbecue_ingredient.ingredient = Ingredient.find_or_initialize_by(title: local_params[:ingredient_attributes][:title])
          barbecue_ingredient.barbecue = @barbecue
          barbecue_ingredient.quantity = local_params[:quantity]
          barbecue_ingredient.save
        end
      end
    end
  end
end

app/helpers/barbecues_helper.rb
module BarbecuesHelper
end

app/views/barbecues/_activity.html.erb
<h3>Activity</h3>
<% @activities.each() do |activity| %>
  <%= render "activities/show", activity: activity %>
<% end %>

app/views/barbecues/_form.html.erb
<div class="container col-md-8">
  <p>Here we will create an event. First give it a name, a brief description, and set the date</p>
  <%= bootstrap_form_for(@barbecue, remote: :true) do |f| %>
    <% if @barbecue.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@barbecue.errors.count, "error") %> prohibited this barbecue from being saved:</h2>

        <ul>
          <% @barbecue.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.text_field :title, hide_label: true, placeholder: "Titre", required: :true %>
    <%= f.text_area :description, hide_label: true, placeholder: "Description" %>
    <%= f.text_field :begin_at, hide_label: true, class: "datetimepicker" %>
    <div class="actions">
      <%= f.submit :class => 'btn btn-success btn-lg'  %>
    </div>
  <% end %>
</div>
<div class="container col-md-4">
</div>

app/views/barbecues/_qrcode.html.erb
<h3>QR Code</h3>
<table class="qr-code">
  <% @qr.modules.each_index do |x| -%>
    <tr>
      <% @qr.modules.each_index do |y| -%>
        <% if @qr.dark?(x,y) -%>
          <td class="black"/>
        <% else -%>
          <td class="white"/>
        <% end -%>
      <% end -%>
    </tr>
  <% end -%>
</table>
<h6>Send a photo to your friends</h6>

app/views/barbecues/_wehave.html.erb
<div>
  <h3>We already have</h3>
  <% if @barbecue.supply.count() > 0 %>
    <ul id="we-have">
      <% @barbecue.supply.map(&:ingredient).uniq.each do |ingredient| %>
        <li>
          <% if @contributions.include?(ingredient.id) %>
            <%= pluralize(@contributions[ingredient.id], ingredient.title) %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% else %>
    Nothing yet
  <% end %>
  <%= render "supplies/onelineform", supply: Supply.new() %>
</div>

app/views/barbecues/_weneed.html.erb
<h3>What we need</h3>
<% if @barbecue.barbecue_ingredient.count() > 0 %>
  <ul id="weeneed">
    <% @barbecue.barbecue_ingredient.each() do |barbecue_ingredient| %>
      <li><%= render "barbecue_ingredients/onelineshow", barbecue_ingredient: barbecue_ingredient, supply: Supply.new() %></li>
    <% end %>
  </ul>
<% else %>
  <p>Nothing yet</p>
<% end %>
<%= render "barbecue_ingredients/onelineform", barbecue_ingredient: BarbecueIngredient.new() %>

app/views/barbecues/_whocomes.html.erb
<h3>Who comes ?</h3>
<% if @attending_users.count() > 0 %>
  <ul>
    <% @attending_users.each() do |user| %>
      <li><%= user.name %></li>
    <% end %>
  </ul>
<% else %>
  Nobody yet
<% end %>

app/views/barbecues/_youbring.html.erb
<h3>You bring</h3>
<ul>
  <% @youbring.each() do |supply| %>
    <li>
      <%= supply.quantity %> <%= link_to(supply.ingredient.title, edit_supply_path(supply)) %> <%= link_to("delete", supply_path(supply), method: :delete) %>
    </li>
<% end %>
</ul>

app/views/barbecues/create.js.erb
window.location = '<%= barbecue_path(@barbecue) %>'
<% if current_or_guest_user.guest and current_or_guest_user.name == "Guest" %>
$('#name-div').modal()
<% end %>

app/views/barbecues/edit.html.erb
<h2><%= @barbecue.title %></h2>

<%= render 'form' %>

<%= link_to 'Show', @barbecue %> |
<%= link_to 'Back', barbecues_path %>

app/views/barbecues/index.html.erb
<h1>Listing barbecues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Begin at</th>
      <th>Organisator</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @barbecues.each do |barbecue| %>
      <tr>
        <td><%= link_to barbecue.title, barbecue %></td>
        <td><%= barbecue.begin_at %></td>
        <td><%= barbecue.user.name %></td>
        <td><% if user_signed_in? && current_user.id == barbecue.user.id %>
          <%= link_to 'Edit', edit_barbecue_path(barbecue) %>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barbecue', new_barbecue_path %>

app/views/barbecues/new.html.erb
<h1>New barbecue</h1>

<%= render 'form' %>

<%= link_to 'Back', barbecues_path %>

app/views/barbecues/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @barbecue.title %></h2>
<div class="container col-md-4 barbecue_details">
  <%= link_to 'I bring something !', new_barbecue_supply_path(@barbecue), class: "btn btn-primary btn-lg" %>
  <p><% if @barbecue.description %>
    <%= @barbecue.description %>
  <% else %>
    No description yet
  <% end %></p>
  <p>Begin at <%= @barbecue.begin_at %></p>
  <p>Organised by <%= @barbecue.user.name %></p>
  <%= render "youbring" %>
  <%= render "qrcode" %>
</div>
<div class="container col-md-8 barbecue_main">
  <div class="row">
    <div class="container col-md-6">
      <%= render "weneed" %>
    </div>
    <div class="container col-md-6">
      <%= render "wehave" %>
    </div>
  </div>
  <%= render "activity" %>
</div>
<% if user_signed_in? and @barbecue.user.id == current_user.id %>
  <%= link_to 'Edit', edit_barbecue_path(@barbecue) %> |
<% end %>
<%= link_to 'Back', barbecues_path %>