config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", sessions: 'sessions', registrations: 'registrations'}
  resources :barbecues
  resources :ingredients

  root 'welcome#index'

  devise_scope :user do
    get '/user/sign_out' => 'devise/sessions#destroy'
  end

  resources :barbecues do
      resources :barbecue_ingredients, shallow: true
  end
  resources :barbecue_ingredients

  resources :barbecues do
      resources :supplies, shallow: true
  end
  resources :supplies

end

app/models/barbecue_ingredient.rb
class BarbecueIngredient < ActiveRecord::Base
  belongs_to :barbecue
  belongs_to :ingredient
  accepts_nested_attributes_for :ingredient, allow_destroy: false, reject_if: lambda {|attributes| (attributes['title'].blank?)}

  after_create do |supply|
    Activity.create(action: "create_ingredient", extra_data: {barbecue_ingredient_id: self.id}, barbecue: self.barbecue, user: self.barbecue.user)
  end
end

app/controllers/barbecue_ingredients_controller.rb
class BarbecueIngredientsController < ApplicationController
  before_action :set_barbecue_ingredient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :new, :create]

  # GET /barbecue_ingredients
  # GET /barbecue_ingredients.json
  def index
    @barbecue_ingredients = BarbecueIngredient.all
  end

  # GET /barbecue_ingredients/1
  # GET /barbecue_ingredients/1.json
  def show
  end

  # GET /barbecue/1/barbecue_ingredients/new
  def new
    @barbecue = Barbecue.find params[:barbecue_id]
    @barbecue_ingredient = BarbecueIngredient.new
  end

  # GET /barbecue_ingredients/1/edit
  def edit
    @barbecue = @barbecue_ingredient.barbecue
  end

  # POST /barbecue_ingredients
  # POST /barbecue_ingredients.json
  def create
    ingredient = Ingredient.find_or_initialize_by(title: barbecue_ingredient_params[:ingredient][:title])
    barbecue = Barbecue.find params[:barbecue_id]
    @barbecue_ingredient = BarbecueIngredient.new(barbecue: barbecue, ingredient: ingredient, quantity: barbecue_ingredient_params[:quantity])

    respond_to do |format|
      if @barbecue_ingredient.save
        format.html { redirect_to @barbecue_ingredient, notice: 'Added #{@barbecue_ingredient.quantity} #{@barbecue_ingredient.ingredient.title} '}
        format.json { render :show, status: :created, location: @barbecue_ingredient }
        format.js
      else
        format.html { render :new }
        format.json { render json: @barbecue_ingredient.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /barbecue_ingredients/1
  # PATCH/PUT /barbecue_ingredients/1.json
  def update
    respond_to do |format|
      if @barbecue_ingredient.update(barbecue_ingredient_params)
        format.html { redirect_to @barbecue_ingredient, notice: 'Barbecue ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @barbecue_ingredient }
      else
        format.html { render :edit }
        format.json { render json: @barbecue_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barbecue_ingredients/1
  # DELETE /barbecue_ingredients/1.json
  def destroy
    @barbecue_ingredient.destroy
    respond_to do |format|
      format.html { redirect_to barbecue_ingredients_url, notice: 'Barbecue ingredient was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barbecue_ingredient
      @barbecue_ingredient = BarbecueIngredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barbecue_ingredient_params
      params.require(:barbecue_ingredient)
        .permit(
                :quantity,
                :barbecue_id,
                ingredient:
                [
                 :id,
                 :title
                ]
                )
    end
end

app/helpers/barbecue_ingredients_helper.rb
module BarbecueIngredientsHelper
end

app/views/barbecue_ingredients/_form.html.erb
<%= bootstrap_form_for(@barbecue_ingredient, layout: :inline) do |f| %>
  <% if @barbecue_ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@barbecue_ingredient.errors.count, "error") %> prohibited this quantity from being saved:</h2>

      <ul>
      <% @barbecue_ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    We need
    <%= f.number_field :quantity, hide_label: :true, placeholder: "2" %>
    <%= f.collection_select :ingredient_id, Ingredient.all, :id, :title, hide_label: :true %>
    at <%= @barbecue.title %>
    <p><%= link_to 'Your ingredient is not listed ? Create it first !', new_ingredient_path %></p>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/barbecue_ingredients/_line_form.html.erb
<div class="form-inline">
  <%= barbecue_ingredient.number_field :quantity, hide_label: :true, placeholder: "quantity" %>
  <%= barbecue_ingredient.fields_for :ingredient, barbecue_ingredient.object.ingredient do |ingredient| %>
    <%= ingredient.text_field :title, hide_label: :true, placeholder: "Ingredient", class: "typeahead" %>
  <% end %>
</div>

app/views/barbecue_ingredients/_onelineform.html.erb
<%= bootstrap_form_for([@barbecue, barbecue_ingredient], remote: true, class: "form-inline") do |f| %>
  <div class="row">
    <div class="col-xs-3">
      <%= f.number_field :quantity, hide_label: :true, placeholder: "quantity", class: "quantity" %>
    </div>
    <div class="col-xs-6">
      <input class="form-control typeahead" name="barbecue_ingredient[ingredient[title]]" placeholder="Type an ingredient" required="required"/>
    </div>
    <div class="col-xs-3">
      <%= f.submit "Add", :class => 'btn btn-success btn-s' %>
    </div>
  </div>
<% end %>

app/views/barbecue_ingredients/_onelineshow.html.erb
<%= pluralize(barbecue_ingredient.quantity, barbecue_ingredient.ingredient.title) %>
<%= bootstrap_form_for([@barbecue, supply], remote: true, class: "form-inline") do |f| %>
  <%= f.hidden_field :quantity, value: barbecue_ingredient.quantity %>
  <input type="hidden" name="supply[ingredient[title]]" value="<%= barbecue_ingredient.ingredient.title %>"/>
  <%= f.submit "Bring !", :class => 'btn btn-primary btn-xs' %>
<% end %>
<%= link_to "Remove", barbecue_ingredient_url(barbecue_ingredient), class: "btn btn-danger btn-xs form-inline", method: :delete, remote: true %>

app/views/barbecue_ingredients/create.js.erb
document.location.reload()

app/views/barbecue_ingredients/destroy.js.erb
document.location.reload()

app/views/barbecue_ingredients/edit.html.erb
<h1>Editing barbecue_ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @barbecue_ingredient %> |
<%= link_to 'Back', barbecue_ingredients_path %>

app/views/barbecue_ingredients/index.html.erb
<h1>Listing quantities</h1>

<table>
  <thead>
    <tr>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @barbecue_ingredients.each do |barbecue_ingredient| %>
      <tr>
        <td><%= barbecue_ingredient.ingredient.title %></td>
        <td><%= link_to barbecue_ingredient.barbecue.title, barbecue_ingredient.barbecue  %></td>
        <td><%= barbecue_ingredient.quantity %></td>
        <td><%= link_to 'Show', barbecue_ingredient %></td>
        <td><%= link_to 'Edit', edit_barbecue_ingredient_path(barbecue_ingredient) %></td>
        <td><%= link_to 'Destroy', barbecue_ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barbecue_ingredient', new_barbecue_ingredient_path %>

app/views/barbecue_ingredients/new.html.erb
<h1>New barbecue_ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', barbecue_ingredients_path %>

app/views/barbecue_ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_barbecue_ingredient_path(@barbecue_ingredient) %> |
<%= link_to 'Back', barbecue_ingredients_path %>